server:
  port: 8766
spring:
  profiles:
    active: db
  application:
    name: data

logging:
  config: classpath:logback.xml


local-config:
  serverIp: http://47.94.128.122:8766/
  httpFilePath: /java/resources/