server:
  port: 8761
spring:
  profiles:
    active: db
  application:
    name: data

logging:
  config: classpath:logback.xml


local-config:
  serverIp: http://39.104.113.229:8761/
  httpFilePath: /java/resources/